# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyphonenumber',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Tel\xe9fono'),
        ),
    ]
