# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20161008_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='/static/img/', verbose_name='Logo'),
        ),
    ]
