# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0, unique=True, verbose_name='C\xf3digo')),
                ('barcode', models.PositiveIntegerField(blank=True, default=0, verbose_name='C\xf3digo de Barras')),
                ('description', models.CharField(default=' ', max_length=255, verbose_name='Descripci\xf3n del producto')),
                ('useinventory', models.BooleanField(default=False, verbose_name='Sistema de Inventarios?')),
                ('inventory', models.FloatField(default=0, verbose_name='Existencia en Inventario')),
                ('minimum', models.FloatField(default=0, verbose_name='M\xednimo en inventario')),
                ('sellmethod', models.CharField(choices=[('uni', 'Por Unidad'), ('bul', 'A Granel'), ('kit', 'En Paquete(kit)')], default='uni', max_length=3, verbose_name='Se Vende Por')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo \u20a1')),
                ('autoprice', models.BooleanField(default=False, verbose_name='Precio Autom\xe1tico?')),
                ('utility', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Utilidad %')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio sin Impuestos \u20a1')),
                ('usetaxes', models.BooleanField(default=False, verbose_name='Usa Impuestos?')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Impuestos %')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Descuento %')),
                ('sellprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta \u20a1')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Familia')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Identificador de Familia')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='ProductSubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Sub-Familia')),
                ('code', models.CharField(max_length=2, verbose_name='Identificador de Sub-Familia')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Sub-Familia',
                'verbose_name_plural': 'Sub-Familias',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='subdepartment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubDepartment', verbose_name='Sub-Familia'),
        ),
    ]
