# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='code',
            field=models.CharField(max_length=2, verbose_name='Identificador de Familia'),
        ),
    ]
