# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20161008_1239'),
        ('products', '0002_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveIntegerField(default=0, verbose_name='C\xf3digo'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('company', 'code'), ('company', 'barcode')]),
        ),
    ]
