# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20161104_1025'),
        ('products', '0002_auto_20161108_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Familia'),
        ),
        migrations.AlterUniqueTogether(
            name='productdepartment',
            unique_together=set([('company', 'name'), ('company', 'code')]),
        ),
    ]
