# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161028_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellmethod',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=3, null=True, verbose_name='Unidad'),
        ),
    ]
