# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161108_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubdepartment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Sub-Familia'),
        ),
        migrations.AlterUniqueTogether(
            name='productsubdepartment',
            unique_together=set([('department', 'code'), ('department', 'name')]),
        ),
    ]
