# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161108_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=4, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='productforsale',
            name='unit',
            field=models.CharField(max_length=4, null=True, verbose_name='Unidad'),
        ),
    ]
