# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161104_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Descripci\xf3n del producto'),
        ),
    ]
