# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161109_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforsale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='products.Product', verbose_name='Producto'),
        ),
    ]
