# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161109_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hasforsale',
            field=models.BooleanField(default=False, verbose_name='Es para Venta?'),
        ),
        migrations.AddField(
            model_name='product',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AddField(
            model_name='productforsale',
            name='iscomposed',
            field=models.BooleanField(default=False, verbose_name='Es Compuesto?'),
        ),
    ]
