# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido'),
        ),
    ]
